management:
  endpoints:
    web:
      exposure:
        include: "*"
debug: false

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/quiz_app
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: never
    username: admin
    password: admin


    jpa:
      show-sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        ddl-auto: update
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl

jwtSecret: quizAppSecretKey
jwtExpirationMs: 86400000