server:
  port: 8050
  servlet:
    context-path: /api/v1/quizapp
spring:
  profiles:
    active: dev
  application:
    name: QuizApp
  jpa:
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  liquibase:
    change-log: classpath:/db/QA_changelog.xml